services:
  python_script:
    container_name: python_script
    build: .
    environment:
      - PRENOM=${PRENOM}
      - NOM=${NOM}
      - TAILLE=${TAILLE}
      - POIDS=${POIDS}
      - SEXE=${SEXE}
      - OBJECTIFPOIDS=${OBJECTIFPOIDS}
      - OBJECTIFPRECEDENT=${OBJECTIFPRECEDENT}